I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 21, in script
    image player_image = "images/" + selected_avatar.lower() + ".png"
  File "game/script.rpy", line 21, in <module>
    image player_image = "images/" + selected_avatar.lower() + ".png"
NameError: name 'selected_avatar' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 21, in script
    image player_image = "images/" + selected_avatar.lower() + ".png"
  File "/home/dell/Downloads/renpy-8.3.2-sdk/renpy/ast.py", line 920, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/home/dell/Downloads/renpy-8.3.2-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 21, in <module>
    image player_image = "images/" + selected_avatar.lower() + ".png"
NameError: name 'selected_avatar' is not defined

Linux-6.5.0-44-generic-x86_64-with-glibc2.38 x86_64
Ren'Py 8.3.2.24090902
Crisis-to-Hope 1.0
Sun Oct  6 08:07:46 2024
